### ISSUE TITLE
Improve performance of type-safe effect cancel token lookup

### ISSUE THREAD

**Issue by jeffersonsetiawan** [tokopedia/RxComposableArchitecture#27]
https://github.com/pointfreeco/swift-composable-architecture/pull/1077

[Use `CancelId.self` as key for cancellation](https://github.com/pointfreeco/swift-composable-architecture/pull/1078)

**Comment by ivanbagaskara** [comment]
https://github.com/tokopedia/RxComposableArchitecture/pull/47
Use CancelId.self: https://github.com/tokopedia/RxComposableArchitecture/pull/48
