### ISSUE TITLE
Old Reducer.pullback CasePath not showing runtimeWarning when the action send is not match with State

### ISSUE THREAD

**Issue by jeffersonsetiawan** [tokopedia/RxComposableArchitecture#99]
When we are using older reducer style and we send action that not represent the current state, e.g: State is in the `.fetching`, but we send action `store.send(.content(.didTap))`, it should sent the runtimeWarning.

```swift
myReducer.pullback(
  state: /State.content,
  action: /Action.content,
  environment: { $0 }
)
```

reported by: @kwekkwek

**Comment by dikasetiadi** [comment]
hi @jeffersonsetiawan , 
do we not use `.optional()` when we do pullback to specific casepath in this issues cases?

**Comment by jeffersonsetiawan** [comment]
in this case, it's StatePath @dikasetiadi , so it automatically be optional

**Comment by dikasetiadi** [comment]
okay got it @jeffersonsetiawan  i think i have found the root cause why the warning is not raised. 
can you help to test using this changes? https://github.com/tokopedia/RxComposableArchitecture/pull/100
